import 'package:campusiq/core/domain/grading_system.dart';

class University {
  final String name;
  final String abbreviation;
  final List<String> aliases;
  final String type;
  final String ownership;
  final String gradingSystemId;
  final String? location;
  final String? logoAssetPath;
  final bool logoNeedsDarkBackground;

  const University({
    required this.name,
    required this.abbreviation,
    this.aliases = const [],
    required this.type,
    required this.ownership,
    required this.gradingSystemId,
    this.location,
    this.logoAssetPath,
    this.logoNeedsDarkBackground = false,
  });

  GradingSystem get gradingSystem => GradingSystem.byId(gradingSystemId);
}

/// All Ghanaian universities mapped to their default grading system.
const ghanaianUniversities = <University>[
  University(
    name: 'Kwame Nkrumah University of Science and Technology',
    abbreviation: 'KNUST',
    type: 'public_university',
    ownership: 'public',
    gradingSystemId: 'cwa',
    location: 'Kumasi',
    logoAssetPath: 'assets/images/universities/knust.png',
  ),
  University(
    name: 'University of Ghana',
    abbreviation: 'UG',
    aliases: ['Legon'],
    type: 'public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/university_of_ghana.png',
    logoNeedsDarkBackground: true,
  ),
  University(
    name: 'University of Cape Coast',
    abbreviation: 'UCC',
    type: 'public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Cape Coast',
    logoAssetPath: 'assets/images/universities/university_of_cape_coast.png',
  ),
  University(
    name: 'University for Development Studies',
    abbreviation: 'UDS',
    type: 'public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Tamale',
    logoAssetPath: 'assets/images/universities/university_for_development_studies.png',
  ),
  University(
    name: 'University of Education, Winneba',
    abbreviation: 'UEW',
    type: 'public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Winneba',
    logoAssetPath: 'assets/images/universities/uew.png',
  ),
  University(
    name: 'University of Mines and Technology',
    abbreviation: 'UMaT',
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'cwa',
    location: 'Tarkwa',
    logoAssetPath: 'assets/images/universities/umat.png',
    logoNeedsDarkBackground: true,
  ),
  University(
    name: 'University of Professional Studies, Accra',
    abbreviation: 'UPSA',
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/upsa.png',
    logoNeedsDarkBackground: true,
  ),
  University(
    name: 'Ghana Institute of Management and Public Administration',
    abbreviation: 'GIMPA',
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt_gimpa',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/gimpa.png',
    logoNeedsDarkBackground: true,
  ),
  University(
    name: 'University of Health and Allied Sciences',
    abbreviation: 'UHAS',
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Ho',
    logoAssetPath: 'assets/images/universities/uhas.png',
  ),
  University(
    name: 'University of Energy and Natural Resources',
    abbreviation: 'UENR',
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Sunyani',
    logoAssetPath: 'assets/images/universities/uenr.png',
  ),
  University(
    name: 'University of Environment and Sustainable Development',
    abbreviation: 'UESD',
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Somanya',
    logoAssetPath: 'assets/images/universities/uesd.png',
  ),
  University(
    name: 'University of Media, Arts and Communication',
    abbreviation: 'UniMAC',
    aliases: ['Ghana Institute of Journalism', 'National Film and Television Institute', 'Ghana Institute of Languages', 'GIJ', 'GIL'],
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/unimac.png',
  ),
  University(
    name: 'Simon Diedong Dombo University of Business and Integrated Development Studies',
    abbreviation: 'UBIDS',
    aliases: ['SDD-UBIDS', 'Wa Campus of UDS', 'SD Dombo University'],
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Wa',
    logoAssetPath: 'assets/images/universities/sd_dombo_university.png',
  ),
  University(
    name: 'Ghana Communication Technology University',
    abbreviation: 'GCTU',
    aliases: ['Ghana Technology University College', 'GTUC'],
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/gctu.png',
  ),
  University(
    name: 'Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development',
    abbreviation: 'AAMUSTED',
    aliases: ['University of Skills Training and Entrepreneurial Development', 'USTED'],
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Kumasi',
    logoAssetPath: 'assets/images/universities/aamusted.png',
  ),
  University(
    name: 'C. K. Tedam University of Technology and Applied Sciences',
    abbreviation: 'CKT-UTAS',
    aliases: ['University for Development Studies Navrongo Campus', 'UDS Navrongo'],
    type: 'specialised_public_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Navrongo',
    logoAssetPath: 'assets/images/universities/ckt_utas.png',
  ),
  University(
    name: 'Accra Technical University',
    abbreviation: 'ATU',
    aliases: ['Accra Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'cgpa_5pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/atu.png',
  ),
  University(
    name: 'Cape Coast Technical University',
    abbreviation: 'CCTU',
    aliases: ['Cape Coast Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'gpa_4pt',
    location: 'Cape Coast',
    logoAssetPath: 'assets/images/universities/cctu.png',
  ),
  University(
    name: 'Kumasi Technical University',
    abbreviation: 'KsTU',
    aliases: ['Kumasi Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'cgpa_5pt',
    location: 'Kumasi',
    logoAssetPath: 'assets/images/universities/kstu.png',
  ),
  University(
    name: 'Takoradi Technical University',
    abbreviation: 'TTU',
    aliases: ['Takoradi Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'cgpa_5pt',
    location: 'Takoradi',
    logoAssetPath: 'assets/images/universities/takoradi_technical_university.png',
  ),
  University(
    name: 'Sunyani Technical University',
    abbreviation: 'STU',
    aliases: ['Sunyani Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Sunyani',
    logoAssetPath: 'assets/images/universities/stu.png',
  ),
  University(
    name: 'Ho Technical University',
    abbreviation: 'HTU',
    aliases: ['Ho Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Ho',
    logoAssetPath: 'assets/images/universities/htu.png',
  ),
  University(
    name: 'Koforidua Technical University',
    abbreviation: 'KTU',
    aliases: ['Koforidua Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Koforidua',
    logoAssetPath: 'assets/images/universities/ktu.png',
  ),
  University(
    name: 'Tamale Technical University',
    abbreviation: 'TaTU',
    aliases: ['Tamale Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Tamale',
    logoAssetPath: 'assets/images/universities/tatu.png',
  ),
  University(
    name: 'Bolgatanga Technical University',
    abbreviation: 'BTU',
    aliases: ['Bolgatanga Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Bolgatanga',
    logoAssetPath: 'assets/images/universities/btu.png',
  ),
  University(
    name: 'Dr. Hilla Limann Technical University',
    abbreviation: 'DHLTU',
    aliases: ['Wa Polytechnic'],
    type: 'technical_university',
    ownership: 'public',
    gradingSystemId: 'uncertain',
    location: 'Wa',
    logoAssetPath: 'assets/images/universities/dhltu.png',
  ),
  University(
    name: 'Ashesi University',
    abbreviation: 'Ashesi',
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'gpa_4pt',
    location: 'Berekuso',
    logoAssetPath: 'assets/images/universities/ashesi_university.png',
  ),
  University(
    name: 'Central University',
    abbreviation: 'CU',
    aliases: ['Central University College'],
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'gpa_4pt',
    location: 'Miotso',
    logoAssetPath: 'assets/images/universities/central_university.png',
  ),
  University(
    name: 'Valley View University',
    abbreviation: 'VVU',
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Oyibi',
    logoAssetPath: 'assets/images/universities/valley_view_university.png',
  ),
  University(
    name: 'Methodist University Ghana',
    abbreviation: 'MUG',
    aliases: ['Methodist University College Ghana'],
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'gpa_4pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/methodist_university_ghana.png',
  ),
  University(
    name: 'Pentecost University',
    abbreviation: 'PU',
    aliases: ['Pentecost University College', 'PUC'],
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/pentecost_university.png',
  ),
  University(
    name: 'Presbyterian University, Ghana',
    abbreviation: 'PUG',
    aliases: ['Presbyterian University College, Ghana', 'PUCG'],
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Abetifi',
    logoAssetPath:
        'assets/images/universities/presbyterian_university_ghana.png',
  ),
  University(
    name: 'Christian Service University',
    abbreviation: 'CSU',
    aliases: ['Christian Service University College', 'CSUC'],
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Kumasi',
    logoAssetPath:
        'assets/images/universities/christian_service_university.png',
  ),
  University(
    name: 'Catholic University of Ghana',
    abbreviation: 'CUG',
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'gpa_4pt',
    location: 'Fiapre',
    logoAssetPath: 'assets/images/universities/catholic_university_ghana.png',
  ),
  University(
    name: 'Academic City University College',
    abbreviation: 'ACity',
    aliases: ['Academic City', 'Academic City University'],
    type: 'private_university_college',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/academic_city_university.png',
  ),
  University(
    name: 'KAAF University',
    abbreviation: 'KAAF',
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Fetteh Kakraba',
    logoAssetPath: 'assets/images/universities/kaaf_university.png',
  ),
  University(
    name: 'Ensign Global University',
    abbreviation: 'EGU',
    aliases: ['Ensign College of Public Health', 'Ensign Global College'],
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Kpong',
    logoAssetPath: 'assets/images/universities/ensign_global_university.png',
  ),
  University(
    name: 'African University College of Communications and Business',
    abbreviation: 'AUCB',
    aliases: ['African University College of Communications', 'AUCC'],
    type: 'private_university_college',
    ownership: 'private',
    gradingSystemId: 'gpa_4pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/aucb.png',
  ),
  University(
    name: 'Wisconsin International University College, Ghana',
    abbreviation: 'WIUC-Ghana',
    aliases: ['WIUC', 'Wisconsin Ghana'],
    type: 'private_university_college',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/wiuc_ghana.png',
  ),
  University(
    name: 'Knutsford University College',
    abbreviation: 'KUC',
    type: 'private_university_college',
    ownership: 'private',
    gradingSystemId: 'gpa_4pt',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/knutsford_university.png',
  ),
  University(
    name: 'Regent University College of Science and Technology',
    abbreviation: 'Regent',
    aliases: ['RUCST'],
    type: 'private_university_college',
    ownership: 'private',
    gradingSystemId: 'uncertain',
    location: 'Accra',
    logoAssetPath: 'assets/images/universities/regent_university.png',
  ),
  University(
    name: 'All Nations University',
    abbreviation: 'ANU',
    type: 'private_university',
    ownership: 'private',
    gradingSystemId: 'cgpa_5pt',
    location: 'Koforidua',
    logoAssetPath: 'assets/images/universities/all_nations_university.png',
  ),
];

const otherUniversity = University(
  name: 'Other',
  abbreviation: 'Other',
  type: 'other',
  ownership: 'other',
  gradingSystemId: 'uncertain',
  location: null,
);

/// Full list including "Other" for the onboarding picker.
const universityPickerOptions = [...ghanaianUniversities, otherUniversity];

University universityByName(String name) {
  for (final uni in ghanaianUniversities) {
    if (uni.name == name) return uni;
  }
  return otherUniversity;
}
